//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplicationSpeech
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emages
    {
        public int imageName { get; set; }
        public byte[] image { get; set; }
    }
}
